version: '3.1'
services:
  # todo-frontend:
  #   image: paulanuschek/todo-frontend:0.0.1
  #   ports:
  #     - "8081:8081"
  #   networks:
  #     - todo-network

  todo-backend:
    image: paulanuschek/todo-backend:0.0.1
    ports:
      - "8080:8080"
    networks:
      - todo-network
    depends_on:
      - todo-database

  todo-database:
    image: paulanuschek/todo-database:0.0.1
    ports:
      - "5432:5432"
    networks:
      - todo-network

networks:
  todo-network: {}