apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: todo-backend
  name: todo-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-backend
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: todo-backend
    spec:
      containers:
      - image: cagritasci/hsr_distributedsystems_24_todo_backend:0.1
        name: hsr-distributedsystems-24-todo-backend-b94f7
        ports:
        - containerPort: 8080
        resources: {}
status: {}
