apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: todo-database
  name: todo-database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-database
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: todo-database
    spec:
      containers:
      - image: cagritasci/hsr_distributedsystems_24_todo_database:0.1
        name: hsr-distributedsystems-24-todo-database-b94f7
        ports:
        - containerPort: 5432
        resources: {}
status: {}
