apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: todo-frontend
  name: todo-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-frontend
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: todo-frontend
    spec:
      containers:
      - image: cagritasci/hsr_distributedsystems_24_todo_frontend:0.1
        name: hsr-distributedsystems-24-todo-frontend-fqhx8
        ports:
        - containerPort: 8081
        resources: {}
status: {}
