apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx
  name: todo-frontend
spec:
  containers:
  - image: cagritasci/hsr_distributedsystems_24_todo_frontend:0.1
    name: todo-frontend
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}