apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx
  name: todo-database
spec:
  containers:
  - image: cagritasci/hsr_distributedsystems_24_todo_database:0.1
    name: todo-database
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
