apiVersion: v1
kind: Service
metadata:
  name: todo-frontend-service
  labels:
    app: todo-frontend
spec:
  type: LoadBalancer
  selector:
     app: todo-frontend
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081